In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression 


In [3]:
# taining dataframe 
data = pd.read_csv('0000000000002429_training_titanic_x_y_train.csv')
data.head()
y_train = np.array(data['Survived'])
y_train

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [14]:
data_train = data.copy()
data_train.head()
del data_train['Survived']
data_train.tail()



Pclass                            Name     Sex   Age  SibSp  Parch  \
663       2             Ilett, Miss. Bertha  female  17.0      0      0   
664       3        Morrow, Mr. Thomas Rowan    male   NaN      0      0   
665       3                   Bing, Mr. Lee    male  32.0      0      0   
666       3     Strandberg, Miss. Ida Sofia  female  22.0      0      0   
667       3  Murphy, Miss. Katherine "Kate"  female   NaN      1      0   

         Ticket     Fare Cabin Embarked  
663  SO/C 14885  10.5000   NaN        S  
664      372622   7.7500   NaN        Q  
665        1601  56.4958   NaN        S  
666        7553   9.8375   NaN        S  
667      367230  15.5000   NaN        Q

In [10]:
def sex(string):
    if string == 'male':
        return 0
    else:
        return 1

In [12]:
def Age(n):
    n = str(n)
    if n != 'nan':
        return int(float(n))
    else:
        return 0
    

In [13]:
def change_dtype(dtype):
    dtype = str(dtype)
    if dtype != 'nan':
        return int(float(dtype))
    else:
        return 0
    

In [15]:
def cabin(n):
    n = str(n)
    if n != 'nan':
        return 1
    else:
        return 0
    

In [16]:
def embarked(n):
    n = str(n)
    if n == 'C':
        return 1
    elif n == 'Q':
        return 2
    elif n == 'S':
        return 3
    else:
        return 0
    

In [18]:
data_train.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  
0      1      0           228414  26.000   NaN        S  
1      0      0         A/5 2466   8.050   NaN        S  
2      0      0           250655  26.000   NaN        S  
3      0      4           349909  21.075   NaN        S  
4      0      0  SOTON/OQ 392076   7.050   NaN        S

In [41]:
new_dataframe = pd.DataFrame()
new_dataframe['Age'] = data_train['Age'].apply(Age)
new_dataframe['Sex'] = data_train['Sex'].apply(sex)
new_dataframe['SibSp'] = data_train['SibSp'].apply(change_dtype)
new_dataframe['Parch'] = data_train['Parch'].apply(change_dtype)
new_dataframe['Fare'] = data_train['Fare'].apply(change_dtype)
new_dataframe['Embarked'] = data_train['Embarked'].apply(embarked)
new_dataframe['Cabin'] = data_train['Cabin'].apply(cabin)
new_dataframe['Pclass'] = data_train['Pclass'].apply(change_dtype)
new_dataframe['Age_Age'] = new_dataframe['Age']*new_dataframe['Age']
new_dataframe['Age_embarked'] = new_dataframe['Age']*new_dataframe['Embarked']

new_dataframe.head()






Age  Sex  SibSp  Parch  Fare  Embarked  Cabin  Pclass  Age_Age  \
0   29    1      1      0    26         3      0       2      841   
1    0    0      0      0     8         3      0       3        0   
2   39    0      0      0    26         3      0       2     1521   
3   29    1      0      4    21         3      0       3      841   
4   25    0      0      0     7         3      0       3      625   

   Age_embarked  
0            87  
1             0  
2           117  
3            87  
4            75

In [44]:
x_train = np.array(new_dataframe)
alg = LogisticRegression()
alg.fit(x_train,y_train)

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [45]:
test_data = pd.read_csv('0000000000002429_test_titanic_x_test.csv')
test_data.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [46]:
test_dataframe = pd.DataFrame()
test_dataframe['Age'] = test_data['Age'].apply(Age)
test_dataframe['Sex'] = test_data['Sex'].apply(sex)
test_dataframe['SibSp'] = test_data['SibSp'].apply(change_dtype)
test_dataframe['Parch'] = test_data['Parch'].apply(change_dtype)
test_dataframe['Fare'] = test_data['Fare'].apply(change_dtype)
test_dataframe['Embarked'] = test_data['Embarked'].apply(embarked)
test_dataframe['Cabin'] = test_data['Cabin'].apply(cabin)
test_dataframe['Pclass'] = test_data['Pclass'].apply(change_dtype)
test_dataframe['Age_Age'] = test_dataframe['Age']*test_dataframe['Age']
test_dataframe['Age_embarked'] = test_dataframe['Age']*test_dataframe['Embarked']
test_dataframe.head()



Age  Sex  SibSp  Parch  Fare  Embarked  Cabin  Pclass  Age_Age  \
0    8    0      1      1    36         3      0       2       64   
1   49    1      0      0    25         3      1       1     2401   
2    0    0      0      0     7         2      0       3        0   
3   24    1      2      1    27         3      0       2      576   
4   36    0      0      0    26         3      1       1     1296   

   Age_embarked  
0            24  
1           147  
2             0  
3            72  
4           108

In [47]:
x_test = np.array(test_dataframe)
y_predict = alg.predict(x_test)
y_predict


array([0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [48]:
alg.score(x_train,y_train)

0.7919161676646707

In [32]:
alg.score(x_test,y_predict)

1.0

In [49]:
np.savetxt('y_prediction_titanic.csv',y_predict,fmt ='%.0f')

In [51]:
alg.predict_proba(x_test)

array([[0.78479674, 0.21520326],
       [0.10002408, 0.89997592],
       [0.83714429, 0.16285571],
       [0.34611928, 0.65388072],
       [0.48991891, 0.51008109],
       [0.85030144, 0.14969856],
       [0.84263022, 0.15736978],
       [0.83714429, 0.16285571],
       [0.30433548, 0.69566452],
       [0.82898988, 0.17101012],
       [0.19775646, 0.80224354],
       [0.82933609, 0.17066391],
       [0.05078561, 0.94921439],
       [0.31991051, 0.68008949],
       [0.74666717, 0.25333283],
       [0.81197786, 0.18802214],
       [0.85149988, 0.14850012],
       [0.88159449, 0.11840551],
       [0.8537124 , 0.1462876 ],
       [0.31056432, 0.68943568],
       [0.36779991, 0.63220009],
       [0.87603638, 0.12396362],
       [0.13292582, 0.86707418],
       [0.25050458, 0.74949542],
       [0.82933609, 0.17066391],
       [0.3714302 , 0.6285698 ],
       [0.76645582, 0.23354418],
       [0.75859207, 0.24140793],
       [0.4883475 , 0.5116525 ],
       [0.31837556, 0.68162444],
       [0.